-- Game modes (0.9.31, Ryan): switches in the Start tab and the Admin tab - Free Repair, No faults, No quirks
-- and Turbo Mode (prizes). Admins switch them; everyone sees which are on.
local t = require("t")
local World = require("world")
local F = require("fixtures")
local p = F.p

local WIN = "Top Gear Challenge"
local function text(pl) return pl.client.im.textOf(WIN) end

t.test("the switches: Start tab and the Admin tab's Game modes box, each with its (?) help; everyone sees what's on", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A, B = w:join("Alice"), w:join("Bob")   -- (Alice is the admin)
  w:chat(A, "/tg menu"); w:chat(B, "/tg menu"); w:step(2.5)
  for _, label in ipairs({ "Free Repair: OFF", "Turbo Mode: OFF", "No faults: OFF", "No quirks: OFF" }) do
    t.ok(A.client.im.hasButton(label), label)
  end
  t.ok(text(A):find("Every repair is free", 1, true), "the (?) explains it")
  A.client.im.click("Free Repair: OFF##mode_freeRepair"); w:step(2.5)
  t.ok(w:chatHas(B, "Game mode: Free Repair is ON."))
  t.eq(w:serverConfig().modes.freeRepair, true, "kept in config.json")
  t.ok(A.client.im.hasButton("Free Repair: ON"))
  t.ok(text(B):find("Game modes: Free Repair", 1, true), "Bob sees it")
  w:chat(B, "/tg mode freerepair off"); t.ok(w:chatHas(B, "That's an admin command."))
  A.client.im.click("Turbo Mode: OFF##mode_turbo"); w:step(0.5)
  t.ok(w:chatHas(B, "Game mode: Turbo Mode is ON."))
  w:assertClean()
end)

t.test("Free Repair: tows, respawns and workshop repairs cost nothing; a tow in an event still disqualifies", function()
  local cfg = F.twoRaces(); cfg.modes = { freeRepair = true }; cfg.workshopEvery = 1
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:chat(A, "/tg start"); w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M")
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready"); w:step(1)
  local cash = w:state(A).cash
  w:damage(A, 3000); w:step(2.5)
  w:chat(A, "/tg respawn"); w:step(2.5)
  t.eq(w:state(A).cash, cash, "a free respawn")
  w:driveAll({ { A, p(500), 40 }, { B, p(500, 3), 30 } }); w:chat(A, "/tg go")
  w:waitFor(function() return w:state(A).phase == "event" end, 10, "GO")
  w:waitFor(function() return w:sawMessage(A, "GO!") end, 10, "the start")
  cash = w:state(A).cash
  w:damage(A, 4000); w:step(2.5)
  w:chat(A, "/tg tow"); w:step(3)
  t.ok(w:chatHas(B, "Alice calls the tow truck (free - Free Repair mode"), "the tow is free")
  t.eq(w:state(A).cash, cash, "nothing charged")
  w:drive(B, p(900), 40)
  w:waitFor(function() return w:state(A).phase == "workshop" end, 15, "the workshop")
  t.ok(w:chatHas(B, "Alice"), "results")
  local dsq = false
  for _, l in ipairs(B.chat) do if l:find("Alice", 1, true) and l:find("DSQ", 1, true) then dsq = true end end
  t.ok(dsq, "the tow still disqualified her from the event")
  w:damage(B, 2000); w:step(2.5)
  local bc = w:state(B).cash
  w:chat(B, "/tg repair")
  t.ok(w:chatHas(A, "Bob had their Ibishu Pessima (1988) repaired (free)."))
  t.eq(w:state(B).cash, bc, "a free workshop repair")
  w:assertClean()
end)

t.test("No faults: every car is New - no condition to pick, no problems; can't be switched once the challenge has started", function()
  local cfg = F.twoRaces(); cfg.modes = { noFaults = true }
  local w = World.new({ files = F.files(cfg) })
  local A = w:join("Alice")
  w:chat(A, "/tg start")
  w:chat(A, "/tg condition death trap")
  t.ok(w:chatHas(A, "switched off"), "no condition to pick")
  w:buy(A, "covet", "base_M"); w:step(3)
  t.eq((w:ui(A).faults or {}).count, nil, "no problems")
  w:chat(A, "/tg mode nofaults off")
  t.ok(w:chatHas(A, "No faults can only be changed before the challenge starts"))
  w:chat(A, "/tg mode freerepair on")
  t.ok(w:chatHas(A, "Game mode: Free Repair is ON."), "Free Repair can change any time")
  w:assertClean()
end)

t.test("No quirks: a Death Trap comes with none", function()
  local cfg = F.twoRaces(); cfg.quirks = { enabled = true }; cfg.modes = { noQuirks = true }
  local w = World.new({ files = F.files(cfg) })
  local A = w:join("Alice")
  w:chat(A, "/tg start"); w:chat(A, "/tg condition death trap"); w:buy(A, "covet", "base_M"); w:step(2.5)
  t.eq((w:ui(A).me or {}).quirks, nil, "no quirks")
  t.ok(#((w:ui(A).faults or {}).levels or {}) > 0, "faults are still on")
  w:assertClean()
end)

t.test("Free Repair: tows and respawns cost no points at the results either", function()
  local cfg = F.twoRaces(); cfg.modes = { freeRepair = true }
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:chat(A, "/tg start"); w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M")
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready"); w:step(1)
  w:chat(A, "/tg tow"); w:step(3)
  t.ok(w:chatHas(B, "Alice calls the tow truck (free - Free Repair mode): "), "no points mentioned")
  t.eq(w:ui(A).helpPoints, 0)
  w:assertClean()
end)

-- Turbo Mode (0.9.32) --------------------------------------------------------------------------------------------
local function turbo(extra)
  local cfg = F.twoRaces(); cfg.modes = { turbo = true }; cfg.workshopEvery = 1
  for k, v in pairs(extra or {}) do cfg[k] = v end
  return cfg
end
local function lineUp(w, A, B)
  w:chat(A, "/tg start"); w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M")
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready"); w:step(1)
  w:drive(A, p(500, 3), 40); w:drive(B, p(500, -3), 40); w:step(1)
end

t.test("Turbo: prizes for arriving first, the cleanest car and last place (a helpful one) - in the glovebox", function()
  local w = World.new({ files = F.files(turbo()) })
  local A, B = w:join("Alice"), w:join("Bob")
  lineUp(w, A, B)
  t.ok(w:chatHas(B, "TURBO: Alice wins a prize for first to arrive at Race One - it's in their glovebox."))
  t.eq(#(w:ui(A).me.glovebox or {}), 1)
  w:chat(A, "/tg go"); w:waitFor(function() return w:sawMessage(A, "GO!") end, 10, "GO")
  w:damage(A, 1500)
  w:driveAll({ { A, p(900), 40 }, { B, p(900), 30 } })
  w:waitFor(function() return w:state(A).phase == "workshop" end, 15, "the workshop")
  t.ok(w:chatHas(A, "TURBO: Bob wins a prize for the cleanest car at the finish"))
  t.ok(w:chatHas(A, "TURBO: Bob wins a prize for last place (a comeback prize)"))
  local good = {}
  for _, pr in ipairs(w:serverConfig().turbo.prizes) do good[pr.id] = pr.good end
  local gb = w:ui(B).me.glovebox
  t.eq(#gb, 2)
  t.ok(good[gb[2].id], "last place's prize is a helpful one")
  w:step(1)   -- (the window draws the new list on its next frame)
  t.ok(B.client.im.textOf(WIN):find("Glovebox (Turbo Mode prizes)", 1, true), "the Status tab's Glovebox")
  w:assertClean()
end)

t.test("Turbo: prizes for the most air time and the biggest crash (all of it, even repaired between)", function()
  local w = World.new({ files = F.files(turbo()) })
  local A, B = w:join("Alice"), w:join("Bob")
  lineUp(w, A, B)
  w:chat(A, "/tg go"); w:waitFor(function() return w:sawMessage(A, "GO!") end, 10, "GO")
  w:jump(B, 2); w:step(3)
  w:jump(A, 0.25); w:step(1)   -- (a bump: too short to count)
  w:damage(A, 800); w:step(3); w:damage(A, 0); w:step(3); w:damage(A, 900); w:step(3)   -- (two hits, repaired between)
  w:driveAll({ { A, p(900), 40 }, { B, p(900), 30 } })
  w:waitFor(function() return w:state(A).phase == "workshop" end, 15, "the workshop")
  local line = w:chatHas(A, "TURBO: Bob wins a prize for the most air time (")
  t.ok(line, "Bob flew")
  -- (1.5 of the 2 s: at the harness's 0.25 s frames the take-off frame (a kick up) and the landing frame don't count)
  t.ok(w:chatHas(A, "most air time (1.5 s)"), "air time measured")
  t.ok(w:chatHas(A, "TURBO: Alice wins a prize for the biggest crash"), "1,700 damage in all, though never more than 900 at once")
  w:assertClean()
end)

t.test("Turbo: no air time or crash prize when nobody flew or crashed enough", function()
  local w = World.new({ files = F.files(turbo()) })
  local A, B = w:join("Alice"), w:join("Bob")
  lineUp(w, A, B)
  w:chat(A, "/tg go"); w:waitFor(function() return w:sawMessage(A, "GO!") end, 10, "GO")
  w:jump(A, 0.5); w:damage(B, 500); w:step(3)
  w:driveAll({ { A, p(900), 40 }, { B, p(900), 30 } })
  w:waitFor(function() return w:state(A).phase == "workshop" end, 15, "the workshop")
  t.ok(not w:chatHas(A, "the most air time"), "half a second isn't enough")
  t.ok(not w:chatHas(A, "the biggest crash"), "500 isn't a crash")
  w:assertClean()
end)

t.test("Turbo admin box: give a player a prize, or a random one; off = a button to turn Turbo Mode on", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:chat(A, "/tg menu"); w:step(2.5)
  t.ok(A.client.im.textOf(WIN):find("Turbo Mode is off.", 1, true))
  A.client.im.click("Turn Turbo Mode on##turboon"); w:step(1)
  t.ok(w:serverConfig().modes.turbo, "switched on")
  w:chat(A, "/tg start"); w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M"); w:step(1)
  A.client.im.click("Bob##tp_Bob"); w:step(0.5)
  A.client.im.click("Taxman##tg_taxman"); w:step(0.5)
  t.ok(w:chatHas(B, "TURBO: Bob wins a prize for the producers' choice"))
  t.eq(w:ui(B).me.glovebox[1].id, "taxman")
  A.client.im.click("A random prize##tgrand"); w:step(0.5)
  t.eq(#w:ui(B).me.glovebox, 2)
  w:step(0.5)
  t.ok(A.client.im.textOf(WIN):find("Glovebox: Taxman, ", 1, true), "the testing list shows Bob's glovebox")
  w:assertClean()
end)

t.test("Turbo testing: any prize's effect at once - the nasty ones on yourself - then cleared", function()
  local w = World.new({ files = F.files(turbo()) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:chat(A, "/tg menu"); w:chat(A, "/tg start"); w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M"); w:step(2.5)
  A.client.im.click("On them: Sabotage: haunted horn##tt_horn"); w:step(1)   -- (Alice is picked: herself)
  t.ok(w:chatHas(A, "TURBO TEST: Alice sabotages Alice: their horn now goes off every time they brake."))
  t.ok(not w:chatHas(B, "TURBO TEST"), "a test isn't told to everyone")
  A.current.electrics.brake = 1; w:step(0.5)
  t.eq(A.current.controls[#A.current.controls], "horn true", "her own horn on braking")
  A.client.im.click("On them: Sabotage: haunted horn##tt_horn"); w:step(0.5)
  t.ok(not w:chatHas(A, "already been got at"), "no once-a-leg limit in a test")
  A.client.im.click("Free engine tune##tt_tune"); w:step(1)
  t.ok(w:state(A).turbo and w:state(A).turbo.tune, "the tune works at once, in the dealership")
  w:step(0.5)
  t.ok(A.client.im.textOf(WIN):find("Effects: engine tune (now), haunted horn", 1, true))
  A.client.im.click("Clear effects##ttclear"); w:step(1)
  t.eq(w:state(A).turbo, nil, "all gone")
  t.eq(A.current.controls[#A.current.controls], "horn false", "the horn stops")
  A.client.im.click("Bob##tp_Bob"); w:step(0.5)
  A.client.im.click("On them: Taxman##tt_taxman"); w:step(0.5)
  t.ok(w:chatHas(B, "TURBO TEST: Alice sends the taxman round to Bob"), "the target is told")
  A.client.im.click("Producers' envelope##tt_envelope"); w:step(0.5)
  t.ok(w:chatHas(A, "TURBO TEST: Bob opens the producers' envelope"), "a helpful one: for the player picked")
  w:assertClean()
end)

t.test("Turbo: the haunted horn (sounds when they brake) and the front-right brake 'upgrade' - until their workshop", function()
  local w = World.new({ files = F.files(turbo()) })
  local A, B = w:join("Alice"), w:join("Bob")
  lineUp(w, A, B)
  w:chat(A, "/tg prize alice horn"); w:chat(A, "/tg prize alice frbrake")
  local n = #w:ui(A).me.glovebox
  w:chat(A, "/tg use " .. (n - 1) .. " bob")
  t.ok(w:chatHas(B, "TURBO: Alice sabotages Bob: their horn now goes off every time they brake!"))
  w:chat(A, "/tg use " .. (n - 1) .. " bob")
  t.ok(w:chatHas(A, "Bob has already been got at this leg - try again later."), "once a leg")
  w:step(1)
  B.current.electrics.brake = 1; w:step(0.5)
  t.eq(B.current.controls[#B.current.controls], "horn true", "braking: the horn")
  B.current.electrics.brake = 0; w:step(0.5)
  t.eq(B.current.controls[#B.current.controls], "horn false", "off the brake: quiet")
  -- next leg: the brake upgrade
  w:chat(A, "/tg go"); w:waitFor(function() return w:sawMessage(A, "GO!") end, 10, "GO")
  w:driveAll({ { A, p(900), 40 }, { B, p(900), 30 } })
  w:waitFor(function() return w:state(A).phase == "workshop" end, 15, "the workshop")
  t.ok(w:chatHas(B, "The workshop has sorted the sabotage on your car"))
  w:chat(A, "/tg next"); w:step(1)   -- (leg 2)
  local gb = w:ui(A).me.glovebox
  for i, pr in ipairs(gb) do if pr.id == "frbrake" then w:chat(A, "/tg use " .. i .. " bob") end end
  t.ok(w:chatHas(B, "Alice kindly upgrades Bob's brakes - the front right one!"))
  w:step(1)
  local base = B.current.wheels[0].brakeTorque
  t.eq(B.current.wheels[1].name, "FR")
  t.eq(B.current.wheels[1].brakeTorque, base * 3, "the front right: 3x")
  t.eq(B.current.wheels[2].brakeTorque, base, "the others as they were")
  t.eq(B.current.wheels[1].hasABS, false, "no ABS on the front right (or it eases the stronger brake off)")
  t.eq(B.current.wheels[1].absOn, false, "the game was told to pick its brake again")
  t.eq(B.current.wheels[2].hasABS, true, "ABS on the others")
  t.eq(B.current.brakeSprings[1], base * 3 * 10, "its brake spring follows the stronger brake")
  w:chat(A, "/tg prize clear bob"); w:step(1)
  t.eq(B.current.wheels[1].brakeTorque, base, "cleared: the front right back to normal")
  t.eq(B.current.wheels[1].hasABS, true, "and its ABS back")
  t.eq(B.current.brakeSprings[1], base * 10)
  w:assertClean()
end)

t.test("Turbo: envelope, taxman, mechanic's favour, engine tune, head start and penalty card", function()
  local cfg = turbo(); cfg.faults = { tiers = false, fires = false, severity = { 1, 1, 1, 1 } }
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:chat(A, "/tg start"); w:chat(A, "/tg condition used"); w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M")
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready"); w:step(1)
  local function use(who, id, target)
    w:chat(A, "/tg prize " .. who.name .. " " .. id)
    w:chat(who, "/tg use " .. #w:ui(who).me.glovebox .. (target and (" " .. target) or ""))
  end
  local a0, b0 = w:state(A).cash, w:state(B).cash
  use(A, "envelope")
  local got = w:state(A).cash - a0
  t.ok(got >= 500 and got <= 2000 and got % 100 == 0, "an envelope: $500-2,000 (" .. got .. ")")
  use(A, "taxman", "bob")
  t.eq(w:state(B).cash, b0 - 500); t.eq(w:state(A).cash, a0 + got + 500)
  use(A, "favour")
  t.ok(w:chatHas(B, "Alice calls in a mechanic's favour: the "), "a problem fixed, free")
  use(A, "tune"); use(A, "headstart"); use(B, "penalty", "alice")
  w:drive(A, p(500, 3), 40); w:drive(B, p(500, -3), 40); w:step(1)
  w:chat(A, "/tg go"); w:waitFor(function() return w:sawMessage(A, "GO!") end, 10, "GO")
  w:step(11)
  t.ok(math.abs(A.current.engine.outputTorqueState - 1.1) < 1e-9, "+10% for the event")
  w:driveAll({ { A, p(900), 40 }, { B, p(900), 30 } })
  w:waitFor(function() return w:state(A).phase == "workshop" end, 15, "the workshop")
  t.ok(w:chatHas(A, "TURBO: Alice's time gets 1 s (a penalty card)."), "3 s on, 2 s off")
  w:step(11)
  t.ok(math.abs(A.current.engine.outputTorqueState - 1) < 1e-9, "the tune is over")
  w:assertClean()
end)
