-- Car classes (0.9.0): import every car's price + attributes, classes of rules + hand-picks, price adjustments,
-- and "needs N faults" in the dealership. Test cars (tests/lib/world.lua MODELS):
--   covet   Japan Hatchback 1988-1996  base_M $4,200 / sport_M $7,800 / gtz_M $14,000, all manual
--   pessima Japan Sedan     1988-1996  base_M $3,900 manual / gl_A $5,100 automatic
--   pickup  US Pickup (Truck) 1990-2010, miramar Japan Sedan 1970-1985, a trailer and cones,
--   modcar  Italy Coupe 1972-1978 - a "mod car" with no game prices (stradale / corsa)
local t = require("t")
local World = require("world")
local F = require("fixtures")

local WIN = "Top Gear Challenge"
local function setup(w, A)
  w:chat(A, "/tg importprices")
  w:step(2)
end
local function jdm(w, A)   -- Japanese cars of the late 80s / 90s
  w:chat(A, "/tg class new jdm")
  w:chat(A, "/tg class rule jdm country Japan")
  w:chat(A, "/tg class rule jdm years 1986-1999")
  w:chat(A, "/tg class rule jdm type Car")
end

t.test("importprices reads every car in the game with its details, without flooding the dealer list", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A = w:join("Alice")
  setup(w, A)
  t.ok(w:chatHas(A, "Imported 10 trim prices from 7 models. Game prices are ON and saved to config.json."))
  t.ok(w:chatHas(A, "2 trims had no game price - kept; give them one with /tg setprice <model/config> <amount>"))
  local dealer = w:serverConfig().dealer
  local e = dealer.gamePrices.covet.gtz_M
  t.eq(e.price, 14000)
  t.eq(e.attrs.Country, "Japan"); t.eq(e.attrs.Transmission, "Manual"); t.eq(e.attrs.Years.min, 1988)
  t.eq(dealer.modelNames.covet, "Ibishu Covet")
  for _, c in ipairs(dealer.cars) do t.ok(c.model ~= "tsfb" and c.model ~= "cones", "props aren't added to the dealer list") end
  local m = dealer.gamePrices.modcar.stradale
  t.ok(m and m.noPrice and m.price == nil, "a trim with no game price is kept")
  t.eq(m.attrs.Country, "Italy", "with its details")
  w:assertClean()
end)

t.test("a class of rules: only matching trims are sold, and the refusal says why", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A, B = w:join("Alice"), w:join("Bob")
  setup(w, A)
  jdm(w, A)
  t.ok(w:chatHas(A, "jdm: Country: Japan; Years 1986-1999; Type: Car - 5 trims, $3,900 to $14,000."))
  w:chat(A, "/tg class rule jdm transmission Manual")
  t.ok(w:chatHas(A, "- 4 trims, $3,900 to $14,000."), "the automatic Pessima drops out")
  w:chat(A, "/tg class use jdm")
  w:chat(A, "/tg start")
  t.ok(w:chatHas(B, "Today's cars: jdm - Country: Japan; Years 1986-1999; Type: Car; Transmission: Manual."))
  t.eq(w:buy(B, "pickup", "d15_M"), nil)
  t.ok(w:chatHas(B, "not in today's class (jdm): Country is United States"))
  t.eq(w:buy(B, "pessima", "gl_A"), nil)
  t.ok(w:chatHas(B, "not in today's class (jdm): Transmission is Automatic"))
  t.eq(w:buy(B, "miramar", "base_M"), nil)
  t.ok(w:chatHas(B, "not in today's class (jdm): Years 1970-1985 (needs 1986-1999)"))
  t.ok(w:buy(B, "pessima", "base_M"), "a matching trim sells")
  t.eq(w:state(B).cash, 10000 - 3900, "at its game price")
  w:step(2.5)
  local s = B.client.im.textOf(WIN)
  t.match(s, "TODAY'S CARS: jdm")
  t.ok(not s:find("D%-Series"), "the pickup isn't offered")
  w:chat(A, "/tg class use none")
  t.ok(w:chatHas(A, "Pick the class before /tg start - not during a challenge."))
  w:assertClean()
end)

t.test("over-budget trims show how many faults would buy them; faults then unlock them", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A = w:join("Alice")
  setup(w, A)
  jdm(w, A)
  w:chat(A, "/tg class price jdm covet/gtz_M 13000")    -- $3,000 over a $10,000 budget: 2 faults ($5,000)
  w:chat(A, "/tg class use jdm")
  w:chat(A, "/tg start")
  w:step(2.5)
  t.match(A.client.im.textOf(WIN), "%$13,000  Ibishu Covet gtz_M  %- needs 2 faults")
  t.ok(not A.client.im.hasButton("Buy##covet_gtz_M") and A.client.im.hasButton("Buy"), "no Buy button until it's affordable")
  t.eq(w:buy(A, "covet", "gtz_M"), nil)
  t.ok(w:chatHas(A, "over your $10,000 budget - 2 more faults would cover it (/tg fault take 2)"))
  w:chat(A, "/tg fault take 2")
  w:step(2.5)
  t.ok(A.client.im.hasButton("Buy"))
  A.client.im.click("Buy##covet_gtz_M")
  w:step(1)
  t.eq(A.current and A.current.configName, "gtz_M")
  t.eq(w:state(A).cash, 10000 + 5000 - 13000, "at the class price")
  w:assertClean()
end)

t.test("hand-picks and a price multiplier", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A = w:join("Alice")
  setup(w, A)
  jdm(w, A)
  w:chat(A, "/tg class exclude jdm covet/sport_M")
  w:chat(A, "/tg class include jdm pickup")
  w:chat(A, "/tg class multiplier jdm 0.5")
  w:chat(A, "/tg class show jdm")
  local s = table.concat(A.chat, "\n")
  t.ok(s:find("$1,950  Ibishu Pessima base_M  [pessima/base_M]", 1, true), "half price")
  t.ok(s:find("[pickup/d15_M]", 1, true), "the pickup is in by hand, though it breaks the rules")
  t.ok(not s:find("[covet/sport_M]", 1, true), "the excluded trim is out")
  w:chat(A, "/tg class clear jdm covet/sport_M")
  w:chat(A, "/tg class show jdm")
  t.ok(table.concat(A.chat, "\n"):find("[covet/sport_M]", 1, true), "clear puts it back")
  w:assertClean()
end)

t.test("no class: the normal dealer list, now with 'needs N faults' too", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A = w:join("Alice")
  w:chat(A, "/tg budget 5000")
  w:chat(A, "/tg start")
  w:step(2.5)
  local s = A.client.im.textOf(WIN)
  t.match(s, "%$7,500  Gavril D%-Series  %- needs 1 fault")
  t.match(s, "%$9,000  Bruckell Moonhawk  %- needs 2 faults")
  w:chat(A, "/tg dealer")
  t.ok(w:chatHas(A, "Gavril D-Series (pickup) - 1 trim, $7,500"))
  w:chat(A, "/tg dealer pickup")
  t.ok(w:chatHas(A, "$7,500  Gavril D-Series  (needs 1 fault)"))
  w:assertClean()
end)

t.test("a class with no cars won't start; the admin tab builds a class with buttons", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A = w:join("Alice")
  setup(w, A)
  w:chat(A, "/tg class new empty")
  w:chat(A, "/tg class use empty")
  w:chat(A, "/tg start")
  t.ok(w:chatHas(A, "Today's class (empty) has no cars"))
  t.eq(w:state(A) and w:state(A).phase or "idle", "idle")

  w:chat(A, "/tg menu"); w:step(2.5)
  local im = A.client.im
  t.ok(im.hasButton("> Edit"), "class list with Edit buttons (the one being edited is marked)")
  im.setText("##newclass", "trucks"); im.click("New class (one word)##clsnew"); w:step(2.5)
  t.ok(w:chatHas(A, "Made class trucks."))
  im.click("Edit##clsedit_trucks"); w:step(2.5)
  t.match(im.textOf(WIN), "CLASS trucks")
  -- the field list starts on Country; pick "Type" (4th) and add "Truck"
  im.click("Type##fld_type"); w:step(0.5)
  im.setText("##clsvalue", "Truck"); im.click("Add rule##clsaddrule"); w:step(2.5)
  t.ok(w:chatHas(A, "trucks: Type: Truck - 2 trims, $6,800 to $12,500."))
  t.ok(im.hasButton("Set price"), "the class's cars, each with a price box")
  im.click("Use##clsuse_trucks"); w:step(1)
  t.ok(w:chatHas(A, "Next challenge's cars: trucks"))
  w:assertClean()
end)

t.test("cars with no game price: a dealership-wide price makes them sellable; a class can still override it", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A, B = w:join("Alice"), w:join("Bob")
  setup(w, A)
  w:chat(A, "/tg setprice list")
  t.ok(w:chatHas(A, "Fanto Bolide stradale [modcar/stradale] - no price"))
  w:chat(A, "/tg class new italy")
  w:chat(A, "/tg class rule italy country Italy")
  t.ok(w:chatHas(A, "italy: Country: Italy - no cars."), "unpriced cars can't be sold yet")
  w:chat(A, "/tg setprice modcar/stradale 6000")
  t.ok(w:chatHas(A, "Fanto Bolide stradale now costs $6,000."))
  w:chat(A, "/tg class show italy")
  t.ok(w:chatHas(A, "italy: Country: Italy - 1 trim, $6,000 to $6,000."))
  w:chat(A, "/tg class use italy")
  w:chat(A, "/tg start")
  t.eq(w:buy(B, "modcar", "corsa"), nil)
  t.ok(w:chatHas(B, "it has no price yet (admin: /tg setprice modcar/corsa <amount>)"))
  t.ok(w:buy(B, "modcar", "stradale"), "the priced one sells")
  t.eq(w:state(B).cash, 4000)
  w:chat(A, "/tg class price italy modcar/corsa 9500")   -- a class price works for an unpriced trim too
  w:chat(A, "/tg class show italy")
  t.ok(w:chatHas(A, "italy: Country: Italy - 2 trims, $6,000 to $9,500."))
  -- the admin window lists the unpriced ones
  w:chat(A, "/tg class edit italy"); w:step(2.5)
  w:chat(A, "/tg class price italy modcar/corsa off"); w:step(2.5)
  t.match(A.client.im.textOf(WIN), "Fanto Bolide corsa  %(no price %- not for sale until it has one%)")
  t.match(A.client.im.textOf(WIN), "Cars without a price %(2%)")
  w:assertClean()
end)

t.test("a dealership-wide price also changes a priced trim, in the normal dealer list too", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A = w:join("Alice")
  setup(w, A)
  w:chat(A, "/tg setprice covet/base_M 3000")
  t.ok(w:chatHas(A, "Ibishu Covet base_M now costs $3,000."))
  w:chat(A, "/tg start")
  w:buy(A, "covet", "base_M")
  t.eq(w:state(A).cash, 7000)
  w:chat(A, "/tg stop")
  w:chat(A, "/tg setprice covet/base_M off")
  t.ok(w:chatHas(A, "Ibishu Covet base_M now costs $4,200 (its game price)."))
  w:assertClean()
end)

t.test("base trims: every car's cheapest factory trim, on its own or with other rules", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A, B = w:join("Alice"), w:join("Bob")
  setup(w, A)
  w:chat(A, "/tg class new basics base")      -- all cars (and trucks), base trims only
  t.ok(w:chatHas(A, "Made class basics: Base trims only; Type: Car, Truck - 4 trims, $3,100 to $6,800."))
  w:chat(A, "/tg setprice modcar/stradale 6000")   -- a mod car with a price now has a base trim
  w:chat(A, "/tg class show basics")
  t.ok(w:chatHas(A, "basics: Base trims only; Type: Car, Truck - 5 trims, $3,100 to $6,800."))
  -- combined with other rules
  jdm(w, A)
  w:chat(A, "/tg class rule jdm trims base")
  t.ok(w:chatHas(A, "jdm: Country: Japan; Years 1986-1999; Type: Car; Base trims only - 2 trims, $3,900 to $4,200."))
  w:chat(A, "/tg class use basics")
  w:chat(A, "/tg start")
  t.eq(w:buy(B, "covet", "sport_M"), nil)
  t.ok(w:chatHas(B, "not in today's class (basics): not the base trim (that's Ibishu Covet base_M)"))
  t.eq(w:buy(B, "tsfb", "base"), nil, "a trailer isn't a car")
  t.ok(w:buy(B, "covet", "base_M"))
  w:assertClean()
end)

t.test("the Admin tab's All cars, base trims button and its price boxes", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A = w:join("Alice")
  setup(w, A)
  w:chat(A, "/tg menu"); w:step(2.5)
  local im = A.client.im
  im.click("All cars, base trims##clsnewbase"); w:step(2.5)
  t.ok(w:chatHas(A, "Made class basetrims: Base trims only; Type: Car, Truck - 4 trims"))
  im.setInt("##unpriced_modcar/stradale", 6500); im.click("Set price##ups_modcar/stradale"); w:step(2.5)
  t.ok(w:chatHas(A, "Fanto Bolide stradale now costs $6,500."))
  t.match(im.textOf(WIN), "Fanto Bolide stradale  %- %$6,500")
  w:assertClean()
end)
