-- Beta testing fixes (0.9.20): Not ready, workshop tows, watching again, back behind the start after a time trial
-- run, restarting an event, admin take/dock/free respawn, trailers at I'm ready.
local t = require("t")
local World = require("world")
local F = require("fixtures")
local p = F.p

local WIN = "Top Gear Challenge"
local function readyGo(cfg) cfg.defaults.readyToGo = true; return cfg end
local function race(extra)
  local e = { name = "Drag", type = "race", timeLimit = 120, start = p(500), checkpoints = { p(900) }, via = {} }
  for k, v in pairs(extra or {}) do e[k] = v end
  return e
end
local function buyAll(w, A, B)
  w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M")
end
local function toStart(w, A, B, at)
  w:chat(A, "/tg start"); buyAll(w, A, B)
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready")
  w:drive(A, p(at or 500, 5), 40); w:drive(B, p(at or 500, -5), 40); w:step(2.5)   -- (arrival order: Alice, Bob)
end

t.test("Not ready: the dealership countdown stops; a race start and the workshop wait again", function()
  local cfg = readyGo(F.config({ race(), race({ name = "Drag Two", start = p(1500), checkpoints = { p(1900) } }) }))
  cfg.defaults.readyCountdown = 5; cfg.workshopEvery = 1
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:chat(A, "/tg start"); buyAll(w, A, B)
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready")
  t.ok(w:chatHas(A, "Everyone's ready! The challenge starts in 5 seconds."))
  w:step(2.5)
  t.ok(A.client.im.hasButton("Not ready - undo"), "the button")
  A.client.im.click("Not ready - undo##unready"); w:step(4)
  t.ok(w:chatHas(A, "Alice isn't ready after all - the countdown is stopped."))
  t.eq(w:state(A).phase, "dealer", "still at the dealership")
  w:chat(A, "/tg ready"); w:step(6)
  t.eq(w:state(A).phase, "travel")
  -- the race start
  w:driveAll({ { A, p(500, 5), 40 }, { B, p(500, -5), 40 } }); w:step(2.5)
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready"); w:chat(B, "/tg unready")
  t.ok(w:chatHas(A, "Bob isn't ready after all."))
  w:chat(A, "/tg go")
  t.ok(w:chatHas(A, "Waiting for Bob to press I'm ready."))
  w:chat(B, "/tg ready"); w:chat(A, "/tg go")
  w:waitFor(function() return w:state(A).phase == "event" end, 10, "GO")
  w:chat(A, "/tg unready")
  t.ok(w:chatHas(A, "Too late - it's already started."))
  w:driveAll({ { A, p(900), 40 }, { B, p(900), 30 } })
  w:waitFor(function() return w:state(A).phase == "workshop" end, 10, "the workshop")
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready"); w:chat(A, "/tg unready")
  t.ok(w:chatHas(A, "Alice isn't done in the workshop after all."))
  w:chat(B, "/tg go")
  t.ok(w:chatHas(B, "Waiting for Alice to press I'm ready."))
  w:assertClean()
end)

t.test("Not ready: a time trial driver takes it back - GO waits", function()
  local cfg = readyGo(F.config({ race({ solo = true }) }))
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  toStart(w, A, B)
  w:chat(A, "/tg ready"); w:step(2.5)
  t.ok(A.client.im.hasButton("Not ready - undo"))
  w:chat(A, "/tg unready"); w:chat(A, "/tg go")
  t.ok(w:chatHas(A, "Alice isn't ready yet - Alice presses I'm ready first."))
  w:assertClean()
end)

t.test("a tow in the workshop goes to the nearest workshop (a car stuck or beyond repair)", function()
  local cfg = F.config({ race(), race({ name = "Drag Two", start = p(1500), checkpoints = { p(1900) } }) })
  cfg.workshopEvery = 1
  cfg.workshopSpots = { { x = 950, y = 100, z = 0, name = "Gas station" }, { x = 5000, y = 0, z = 0, name = "Far" } }
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  toStart(w, A, B); w:chat(A, "/tg go")
  w:waitFor(function() return w:state(A).phase == "event" end, 10, "GO")
  w:driveAll({ { A, p(900), 40 }, { B, p(900), 30 } })
  w:waitFor(function() return w:state(A).phase == "workshop" end, 10, "the workshop")
  w:drive(A, p(1200, -300), 30)   -- stuck in a ditch on the way
  w:chat(A, "/tg tow"); w:step(3)
  t.ok(w:chatHas(A, "towed to the workshop at Gas station"))
  local pos = A.current.pos
  t.ok(math.abs(pos.x - 950) < 1 and math.abs(pos.y - 100) < 1, "at the gas station")
  t.eq(w:ui(A).me.inShop, true, "in the workshop")
  w:chat(B, "/tg tow"); w:step(3)
  t.ok(math.abs(B.current.pos.x - 950) > 3, "the next tow parks beside it, not on top")
  w:assertClean()
end)

t.test("watching: Back to my car keeps a button to watch the driver again", function()
  local cfg = F.config({ race({ solo = true }) })
  cfg.defaults.watchRunner = true
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  toStart(w, A, B)   -- (arrival order: Alice first)
  w:chat(A, "/tg go")
  w:waitFor(function() return B.viewing ~= nil end, 10, "Bob watching")
  B.client.im.click("Back to my car##unwatch"); w:step(0.5)
  t.eq(B.viewing, nil, "in his car")
  t.ok(B.client.im.hasButton("Watch Alice"), "and the button to go back to watching")
  B.client.im.click("Watch Alice##rewatch"); w:step(0.5)
  t.eq(B.viewing, A.current, "watching again")
  w:assertClean()
end)

t.test("time trial: a finished driver's car goes behind the start after a 5 s countdown, then the next run", function()
  local cfg = F.config({ race({ solo = true }) })
  cfg.defaults.backToStartSeconds = 5
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  toStart(w, A, B); w:chat(A, "/tg go")
  w:waitFor(function() return w:sawMessage(A, "Alice: GO!") end, 10, "Alice's GO")
  w:drive(A, p(900), 40); w:step(1)
  t.ok(w:sawMessage(A, "Back to the start in"), "the countdown on her screen")
  t.ok(not w:sawMessage(B, "Bob: GO!") and not w:chatHas(B, "Bob is up"), "Bob waits")
  t.ok(A.current.pos.x > 850, "her car is still at the finish")
  w:step(5)
  t.ok(w:chatHas(A, "Your car's been moved behind the start line - as it is, no repairs."))
  t.ok(A.current.pos.x < 500 - 30, "behind the start line (the start at x = 500, the track runs +x)")
  t.ok(w:chatHas(B, "Bob is up"), "then Bob's turn")
  w:assertClean()
end)

t.test("admin: Restart event - every car back to the start, runs wiped, then Ready and GO again", function()
  local cfg = readyGo(F.config({ race() }))
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  toStart(w, A, B)
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready"); w:chat(A, "/tg go")
  w:waitFor(function() return w:sawMessage(A, "GO!") end, 10, "GO")
  w:driveAll({ { A, p(800), 40 }, { B, p(700), 30 } })
  w:step(2.5)
  t.ok(A.client.im.hasButton("Restart event"), "the Admin tab button")
  w:chat(A, "/tg restartevent"); w:step(3)
  t.ok(w:chatHas(B, "Drag is restarted - your cars are going back to the start line as they are."))
  t.eq(w:state(A).phase, "travel")
  t.ok(math.abs(A.current.pos.x - 500) < 15 and math.abs(B.current.pos.x - 500) < 15, "both at the start")
  w:chat(A, "/tg go")
  t.ok(w:chatHas(A, "Waiting for Alice, Bob to press I'm ready."), "ready again first")
  w:chat(A, "/tg restartevent")
  t.ok(w:chatHas(A, "There's no event running to restart."))
  w:assertClean()
end)

t.test("admin: Take cash, Dock points and a free respawn from the Players box", function()
  local w = World.new({ files = F.files(F.config({ race() })) })
  local A, B = w:join("Alice"), w:join("Bob")
  toStart(w, A, B)
  local cash = w:state(B).cash
  w:step(2.5)   -- (the window opened by itself when the challenge started)
  A.client.im.click("Bob##pl_Bob"); w:step(0.5)
  A.client.im.setInt("Cash##admcash", 700); A.client.im.setInt("Points##admpts", 2); w:step(0.5)
  A.client.im.click("Take##admtake"); w:step(0.5)
  t.ok(w:chatHas(B, "The producers take $700 from Bob."))
  t.eq(w:state(B).cash, cash - 700)
  A.client.im.click("Dock##admdock"); w:step(0.5)
  t.eq(w:state(B).points, -2)
  w:damage(B, 3000); w:step(2.5)
  A.client.im.click("Free respawn##admrespawn"); w:step(3)
  t.ok(w:chatHas(B, "The producers give Bob a free respawn."))
  t.eq(B.current.damage, 0, "repaired")
  t.eq(w:state(B).cash, cash - 700, "free")
  t.noLine(B.chat, "billed")
  w:assertClean()
end)

t.test("trailer event: each trailer is dropped when its driver presses I'm ready - not all at once on arrival", function()
  local cfg = readyGo(F.config({ { name = "Trailer Delivery", type = "trailer", timeLimit = 300, start = p(500),
                                   checkpoints = { p(700), p(900) }, via = {} } }))
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  toStart(w, A, B); w:step(3)
  t.noLine(A.chat, "Your trailer and its load are being dropped", "not on arrival")
  w:chat(A, "/tg ready"); w:step(3)
  t.ok(w:chatHas(A, "Your trailer and its load are being dropped behind you"), "Alice's at her I'm ready")
  t.noLine(B.chat, "Your trailer and its load are being dropped", "Bob isn't ready yet")
  w:chat(B, "/tg ready"); w:step(3)
  t.ok(w:chatHas(B, "Your trailer and its load are being dropped behind you"))
  w:assertClean()
end)

t.test("admin: Bring to me - a player's car, as it is, 50 m in front of the admin, facing the same way", function()
  local w = World.new({ files = F.files(F.config({ race() })) })
  local A, B = w:join("Alice"), w:join("Bob")
  toStart(w, A, B)
  w:place(A, p(2000, 300, 12), math.pi / 2); w:step(1.5)   -- Alice faces +y (up a hill: z 12)
  w:damage(B, 2000); w:step(2.5)
  A.client.im.click("Bob##pl_Bob"); w:step(0.5)
  A.client.im.click("Bring to me##admbring"); w:step(3)
  t.ok(w:chatHas(A, "Bringing Bob's car to 50 m in front of you."))
  local pos = B.current.pos
  t.ok(math.abs(pos.x - 2000) < 0.5 and math.abs(pos.y - 350) < 0.5, "50 m ahead of her")
  t.ok(math.abs(pos.z - 0.5) < 0.01, "on the ground his game found, not at her height")
  t.ok(B.current.damage >= 2000, "as it is - no repair")
  w:assertClean()
end)

t.test("admin: Bring to me to the start isn't an arrival - no bonus, no first place, no Turbo prize (0.9.35)", function()
  local cfg = F.config({ race() }); cfg.modes = { turbo = true }
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:chat(A, "/tg start"); buyAll(w, A, B)
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready"); w:step(1)
  w:place(A, p(500, -50), math.pi / 2); w:step(1.5)   -- (Alice faces +y: 50 m ahead of her is the start)
  local cash = w:state(B).cash
  A.client.im.click("Bob##pl_Bob"); w:step(0.5)
  A.client.im.click("Bring to me##admbring"); w:step(3)
  t.ok(w:chatHas(B, "Bob is at Drag (brought by an admin - no arrival bonus or prize)"))
  t.ok(not w:chatHas(B, "TURBO: Bob wins"), "no prize for being brought")
  t.eq(w:state(B).cash, cash, "no bonus")
  w:drive(A, p(500, 5), 40); w:step(2.5)
  t.ok(w:chatHas(B, "Alice arrives at Drag (1st)"), "the first real arrival is still 1st")
  t.ok(w:chatHas(B, "TURBO: Alice wins a prize for first to arrive at Drag"))
  w:assertClean()
end)

t.test("admin: Rerun a finished event - results taken back, the workshop after it cancelled, back to its start (0.9.35)", function()
  local cfg = readyGo(F.config({ race(), race({ name = "Drag Two", start = p(1500), checkpoints = { p(1900) } }) }))
  cfg.modes = { turbo = true }; cfg.workshopEvery = 1
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:chat(A, "/tg menu")
  toStart(w, A, B)
  local before = { A = w:state(A).cash, B = w:state(B).cash, ga = #(w:ui(A).me.glovebox or {}), gb = #(w:ui(B).me.glovebox or {}) }
  local function run()
    w:chat(A, "/tg ready"); w:chat(B, "/tg ready"); w:chat(A, "/tg go")
    w:waitFor(function() return w:sawMessage(A, "GO!") end, 10, "GO")
    w:driveAll({ { A, p(900), 40 }, { B, p(900), 30 } })
    w:waitFor(function() return w:state(A).phase == "workshop" end, 15, "the workshop")
    w:step(1)
  end
  run()
  t.ok(w:state(A).cash > before.A, "Alice won prize money")
  t.ok(#w:ui(B).me.glovebox > before.gb, "Bob won Turbo prizes (cleanest, last place)")
  t.ok(A.client.im.hasButton("Rerun Drag"), "the Challenge box button")
  A.client.im.click("Rerun Drag##rerunevent"); w:step(0.5); A.client.im.click("Really? Rerun Drag##rerunevent"); w:step(3)
  t.ok(w:chatHas(B, "Drag will be run again - its results are taken back (prize money, points, Turbo prizes)"))
  t.eq(w:state(A).phase, "travel")
  t.eq(w:state(A).cash, before.A, "Alice's prize money taken back")
  t.eq(w:state(B).cash, before.B, "Bob's too")
  t.eq(#(w:ui(B).me.glovebox or {}), before.gb, "the Turbo prizes those results gave")
  t.eq(#(w:ui(A).me.glovebox or {}), before.ga)
  for _, s in ipairs(w:ui(A).standings) do t.eq(s.points, 0, s.name .. "'s points"); t.eq(s.wins, 0, s.name .. "'s wins") end
  t.ok(math.abs(A.current.pos.x - 500) < 15 and math.abs(B.current.pos.x - 500) < 15, "both at Drag's start")
  t.ok(not A.client.im.hasButton("Rerun Drag"), "once")
  -- run it again: scored once, and the workshop opens again as workshop 1
  run()
  local wins = 0
  for _, s in ipairs(w:ui(A).standings) do wins = wins + s.wins end
  t.eq(wins, 1, "one win in all")
  t.ok(w:chatHas(A, "Workshop inspection"), "inspected again")
  w:chat(A, "/tg next"); w:step(1)   -- (the workshop closes: on the way to Drag Two)
  t.ok(A.client.im.hasButton("Rerun Drag"), "still possible on the way to the next event")
  w:drive(A, p(1500, 5), 40); w:drive(B, p(1500, -5), 40); w:step(2.5)
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready"); w:chat(A, "/tg go")
  w:waitFor(function() return w:sawMessage(A, "GO!") end, 10, "GO")
  w:chat(A, "/tg rerunevent")
  t.ok(w:chatHas(A, "An event is running - Restart event runs it again."), "not once the next event has started")
  -- the cancelled workshop's inspection is gone: at the finale, 2 inspections (workshop 1 + the finale), not 3
  w:driveAll({ { A, p(1900), 40 }, { B, p(1900), 30 } })
  w:waitFor(function() return w:state(A).phase == "finale" end, 15, "the finale")
  w:drive(A, p(5000), 40)
  t.ok(w:chatHas(A, "Drivability (average of 2 inspections)"), "the rerun's workshop counted once")
  w:assertClean()
end)

t.test("event starts face a way: Set start here takes the way the admin's car points; drivers see an arrow", function()
  local w = World.new({ files = F.files(F.config({ race() })) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:buy(A, "covet", "base_M")
  w:place(A, p(500, 0), math.pi / 2); w:step(1.5)   -- facing +y (the first checkpoint is +x: the arrow says otherwise)
  w:chat(A, "/tg setstart 1")
  t.ok(w:chatHas(A, "event 1 start set (500.0, 0.0, 0.0), facing the way your car points"))
  local sd = w:serverConfig().events[1].startDir
  t.ok(math.abs(sd.x) < 0.01 and math.abs(sd.y - 1) < 0.01, "stored")
  w:assertClean()
  w = World.new({ files = w.files })   -- (the saved course, in a fresh challenge)
  A, B = w:join("Alice"), w:join("Bob")
  w:chat(A, "/tg start"); buyAll(w, A, B)
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready"); w:step(2.5)
  local face = w:state(A).target.face
  t.ok(face and math.abs(face.y - 1) < 0.01, "the leg's target carries the way to face")
  local heads = 0
  for _, cy in ipairs(A.client.cylinders) do
    if math.abs(cy.a.x - 500) < 0.01 and math.abs(cy.a.y - 5) < 0.01 and cy.b.y < cy.a.y and cy.r == 0.15 then heads = heads + 1 end
  end
  t.eq(heads, 2, "an arrowhead 5 m up +y from the start")
  w:assertClean()
end)

t.test("a start set before 0.9.23 (no direction) faces its first checkpoint", function()
  local w = World.new({ files = F.files(F.config({ race() })) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:chat(A, "/tg start"); buyAll(w, A, B)
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready"); w:step(2.5)
  local face = w:state(A).target.face
  t.ok(face and math.abs(face.x - 1) < 0.01, "towards the first checkpoint (+x)")
  w:assertClean()
end)
