-- Testing one event without a whole challenge (0.9.13, the course builder's Test event / Quick travel / Stop event)
local t = require("t")
local World = require("world")
local F = require("fixtures")
local p = F.p

local WIN = "Top Gear Challenge"
local function course()
  return F.config({
    { name = "Drag", type = "race", timeLimit = 120, start = p(500), checkpoints = { p(700), p(900) }, via = {} },
    { name = "Hill Climb", type = "race", solo = true, timeLimit = 120, start = p(1500), checkpoints = { p(1900) }, via = {} },
    { name = "Unfinished", type = "race", timeLimit = 120, via = {} },
  })
end

t.test("Test event: the event on its own from its countdown - everyone in a car races, results, then back to normal", function()
  local w = World.new({ files = F.files(course()) })
  local A, B = w:join("Alice"), w:join("Bob")   -- (Alice is the admin)
  w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M")
  w:driveAll({ { A, p(500, 5), 40 }, { B, p(500, -5), 40 } }); w:step(1.5)
  w:chat(A, "/tg menu"); w:step(2.5)
  t.ok(A.client.im.hasButton("Test\n event") or A.client.im.hasButton(" Test\nevent"), "the Test event button")
  A.client.im.click("##big_testevent"); w:step(0.5)
  t.ok(w:chatHas(A, "TEST EVENT: Drag (event 1) - 2 drivers, from the start line. /tg testevent stop ends it."))
  t.eq(w:state(A).phase, "countdown", "straight to the countdown")
  w:waitFor(function() return w:state(A).phase == "event" end, 10, "GO")
  w:driveAll({ { A, p(900), 40 }, { B, p(900), 30 } })
  w:waitFor(function() return w:state(A).phase == "idle" end, 10, "back to normal")
  t.ok(w:chatHas(A, "1st  Alice"), "results")
  t.ok(w:chatHas(A, "Test event over - back to normal."))
  t.noLine(A.chat, "WORKSHOP"); t.noLine(A.chat, "LEG 2")
  t.ok(A.current and B.current, "everyone keeps their car")
  t.ok(not (w.files["Resources/Server/TopGear/session.json"] or ""):find("Drag", 1, true), "nothing saved to resume")
  w:assertClean()
end)

t.test("Test event in time trial mode, Stop event, and the things it refuses", function()
  local w = World.new({ files = F.files(course()) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:chat(A, "/tg testevent 1")
  t.ok(w:chatHas(A, "Nobody's in a car - get in one first."))
  w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M"); w:step(1.5)
  w:chat(A, "/tg testevent 3")
  t.ok(w:chatHas(A, "Can't test event 3 yet:"), "an unfinished event")
  w:chat(B, "/tg testevent 2")
  t.noLine(B.chat, "TEST EVENT", "admins only")
  w:driveAll({ { A, p(1500, 5), 60 }, { B, p(1500, -5), 60 } })
  w:chat(A, "/tg testevent 2")
  t.ok(w:chatHas(A, "One at a time - running order: Alice, Bob."), "time trial mode: one at a time")
  w:waitFor(function() return w:sawMessage(A, "Alice: GO!") end, 10, "Alice's GO")
  w:chat(A, "/tg testevent stop")
  t.ok(w:chatHas(A, "Test event stopped - back to normal."))
  t.eq(w:state(A).phase, "idle")
  w:chat(A, "/tg testevent stop")
  t.ok(w:chatHas(A, "No test event is running."))
  -- not during a real challenge
  w:chat(A, "/tg start force")   -- (force: event 3 is unfinished on purpose)
  w:chat(A, "/tg testevent 1"); w:chat(A, "/tg quicktravel 1")
  t.ok(w:chatHas(A, "Test events only run when no challenge is going (/tg stop first)."))
  t.ok(w:chatHas(A, "Quick travel only works when no challenge is going."))
  w:assertClean()
end)

t.test("Quick travel: your car to the event's start, facing the first checkpoint", function()
  local w = World.new({ files = F.files(course()) })
  local A = w:join("Alice")
  w:buy(A, "covet", "base_M"); w:drive(A, p(3000, 200), 60); w:step(1.5)
  w:chat(A, "/tg quicktravel 2"); w:step(0.5)
  t.ok(w:chatHas(A, "Off to event 2's start."))
  t.eq(A.current.pos.x, 1500); t.eq(A.current.pos.y, 0)
  t.ok(math.abs(math.cos(A.current.yaw or 0) - 1) < 1e-6 or math.abs(math.sin(A.current.yaw or 0) - 1) < 1e-6,
    "facing along the course: " .. tostring(A.current.yaw))
  w:chat(A, "/tg quicktravel 3")
  t.ok(w:chatHas(A, "event 3 has no start yet."))
  w:assertClean()
end)

t.test("checkpoints are 5 m (12 m until 0.9.13): saved configs at 12 move once, an admin's own value stays", function()
  t.eq(World.new():serverConfig().defaults.cpRadius, 5)
  local function load(r)
    local cfg = course(); cfg.defaults.cpRadius = r
    return World.new({ files = F.files(cfg) }):serverConfig().defaults.cpRadius
  end
  t.eq(load(12), 5)
  t.eq(load(8), 8, "a custom radius isn't touched")
end)

t.test("Test event, trailer delivery: the first GO brings everyone's trailer to hitch up; then GO per driver in a time trial", function()
  local cfg = F.config({ { name = "Trailer Delivery", type = "trailer", solo = true, timeLimit = 300,
                           start = p(500), checkpoints = { p(700), p(900) }, via = {} } })
  cfg.defaults = { readyCountdown = 0, soloGo = true, readyToGo = false }
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M")
  w:driveAll({ { A, p(500, 5), 40 }, { B, p(500, -5), 40 } }); w:step(1.5)
  w:chat(A, "/tg testevent 1"); w:step(6)
  t.ok(w:chatHas(A, "Trailers are on their way - hitch up, then press GO for the first run (one at a time)."))
  local function trailers(pl) local n = 0 for _, v in pairs(pl.vehicles) do if v.model == "tsfb" then n = n + 1 end end return n end
  t.eq(trailers(A), 1, "Alice's trailer"); t.eq(trailers(B), 1, "Bob's trailer")
  t.eq(w:state(A).phase, "travel", "nothing starts until GO - time to hitch up")
  t.noLine(A.chat, "running order")
  w:hitch(A); w:hitch(B)
  w:chat(A, "/tg menu"); w:step(2.5)
  t.eq(w:ui(A).goName, "Alice")
  t.ok(A.client.im.hasButton("GO: Alice"), "the next GO is for the first driver (Alice pressed Test event)")
  w:chat(B, "/tg go")
  t.ok(w:chatHas(A, "running order: Alice, Bob."))
  w:waitFor(function() return w:sawMessage(A, "Alice: GO!") end, 10, "Alice's run")
  w:drive(A, p(900), 40)
  w:step(2.5)
  t.ok(w:chatHas(A, "Bob is up (last run) - Bob presses GO when ready."), "then Bob, on his own GO")
  w:chat(A, "/tg testevent stop")
  t.eq(trailers(A) + trailers(B), 0, "Stop event cleans the trailers up")
  w:assertClean()
end)

t.test("Test event, trailer delivery in race mode: hitch up first, then one GO starts everyone", function()
  local cfg = F.config({ { name = "Trailer Delivery", type = "trailer", timeLimit = 300,
                           start = p(500), checkpoints = { p(700), p(900) }, via = {} } })
  local w = World.new({ files = F.files(cfg) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M")
  w:driveAll({ { A, p(500, 5), 40 }, { B, p(500, -5), 40 } }); w:step(1.5)
  w:chat(A, "/tg testevent 1"); w:step(6)
  t.ok(w:chatHas(A, "Trailers are on their way - hitch up, then press GO to start everyone."))
  t.eq(w:state(A).phase, "travel")
  w:hitch(A); w:hitch(B)
  w:chat(A, "/tg go")
  t.eq(w:state(A).phase, "countdown", "everyone's countdown")
  w:assertClean()
end)
