-- Air time events (0.9.35, Ryan): laid out like a race, one at a time by default; the most time in the air over the
-- run wins (the client's free-fall measure - the harness's w:jump). Jumps before or after your run don't count.
local t = require("t")
local World = require("world")
local F = require("fixtures")
local p = F.p

local function course()
  return F.config({ { name = "Big Air", type = "airtime", timeLimit = 300, start = p(500), checkpoints = { p(700), p(900) }, via = {} } })
end

t.test("Air time: one at a time, the most air over the run wins; jumps outside your run don't count", function()
  local w = World.new({ files = F.files(course()) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:chat(A, "/tg start"); w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M")
  w:chat(A, "/tg ready"); w:chat(B, "/tg ready"); w:step(1)
  w:drive(A, p(500, 3), 40); w:drive(B, p(500, -3), 40); w:step(1)
  w:chat(A, "/tg go")
  t.ok(w:chatHas(A, "running order: Alice, Bob."), "a time trial by default")
  w:waitFor(function() return w:sawMessage(A, "Alice: GO!") end, 10, "Alice's GO")
  w:step(0.5)
  w:jump(B, 3); w:step(4)   -- (Bob, waiting his turn: doesn't count)
  w:jump(A, 1); w:step(2)
  t.ok((w:state(A).airRun or 0) > 0, "the HUD's live counter")
  w:drive(A, p(700), 40); w:drive(A, p(900), 40)
  w:waitFor(function() return w:sawMessage(B, "Bob: GO!") end, 15, "Bob's GO")
  w:step(0.5)
  w:jump(B, 2); w:step(3)
  w:drive(B, p(700), 40); w:drive(B, p(900), 40)
  w:waitFor(function() return w:state(A).phase ~= "event" end, 15, "the results")
  t.ok(w:chatHas(A, "1st  Bob - 1.5 s in the air"), "Bob: 2 s jump (1.5 s at the harness's 0.25 s frames)")
  t.ok(w:chatHas(A, "2nd  Alice - 0.5 s in the air"), "Alice: 1 s jump; Bob's jump while waiting didn't count")
  w:assertClean()
end)

t.test("Air time: in the type list, built like a race (checkpoints), the road guide goes the whole way", function()
  local w = World.new({ files = F.files(course()) })
  local A = w:join("Alice")
  w:chat(A, "/tg menu"); w:step(2.5)
  t.ok(A.client.im.hasButton("> Air time"), "the course builder's type button (selected)")
  t.ok(A.client.im.hasButton("    Add\ncheckpoint"), "checkpoints, like a race")
  w:chat(A, "/tg start"); w:buy(A, "covet", "base_M"); w:chat(A, "/tg ready"); w:step(1)
  w:drive(A, p(500, 3), 40); w:step(1)
  t.eq(#(A.client.route or {}), 3, "the preview: start, both checkpoints")
  w:chat(A, "/tg stop"); w:step(1)
  local n = #A.chat
  w:chat(A, "/tg addevent airtime")
  local said = table.concat(A.chat, "\n", n + 1)
  t.ok(said:find("Air Time", 1, true), "/tg addevent airtime: " .. said)
  w:assertClean()
end)
