-- Testing one event without a whole challenge (0.9.13, the course builder's Test event / Quick travel / Stop event)
local t = require("t")
local World = require("world")
local F = require("fixtures")
local p = F.p

local WIN = "Top Gear Challenge"
local function course()
  return F.config({
    { name = "Drag", type = "race", timeLimit = 120, start = p(500), checkpoints = { p(700), p(900) }, via = {} },
    { name = "Hill Climb", type = "race", solo = true, timeLimit = 120, start = p(1500), checkpoints = { p(1900) }, via = {} },
    { name = "Unfinished", type = "race", timeLimit = 120, via = {} },
  })
end

t.test("Test event: the event on its own from its countdown - everyone in a car races, results, then back to normal", function()
  local w = World.new({ files = F.files(course()) })
  local A, B = w:join("Alice"), w:join("Bob")   -- (Alice is the admin)
  w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M")
  w:driveAll({ { A, p(500, 5), 40 }, { B, p(500, -5), 40 } }); w:step(1.5)
  w:chat(A, "/tg menu"); w:step(2.5)
  t.ok(A.client.im.hasButton("Test\n event") or A.client.im.hasButton(" Test\nevent"), "the Test event button")
  A.client.im.click("##big_testevent"); w:step(0.5)
  t.ok(w:chatHas(A, "TEST EVENT: Drag (event 1) - 2 drivers, from the start line. /tg testevent stop ends it."))
  t.eq(w:state(A).phase, "countdown", "straight to the countdown")
  w:waitFor(function() return w:state(A).phase == "event" end, 10, "GO")
  w:driveAll({ { A, p(900), 40 }, { B, p(900), 30 } })
  w:waitFor(function() return w:state(A).phase == "idle" end, 10, "back to normal")
  t.ok(w:chatHas(A, "1st  Alice"), "results")
  t.ok(w:chatHas(A, "Test event over - back to normal."))
  t.noLine(A.chat, "WORKSHOP"); t.noLine(A.chat, "LEG 2")
  t.ok(A.current and B.current, "everyone keeps their car")
  t.ok(not (w.files["Resources/Server/TopGear/session.json"] or ""):find("Drag", 1, true), "nothing saved to resume")
  w:assertClean()
end)

t.test("Test event in time trial mode, Stop event, and the things it refuses", function()
  local w = World.new({ files = F.files(course()) })
  local A, B = w:join("Alice"), w:join("Bob")
  w:chat(A, "/tg testevent 1")
  t.ok(w:chatHas(A, "Nobody's in a car - get in one first."))
  w:buy(A, "covet", "base_M"); w:buy(B, "pessima", "base_M"); w:step(1.5)
  w:chat(A, "/tg testevent 3")
  t.ok(w:chatHas(A, "Can't test event 3 yet:"), "an unfinished event")
  w:chat(B, "/tg testevent 2")
  t.noLine(B.chat, "TEST EVENT", "admins only")
  w:driveAll({ { A, p(1500, 5), 60 }, { B, p(1500, -5), 60 } })
  w:chat(A, "/tg testevent 2")
  t.ok(w:chatHas(A, "One at a time - running order: Alice, Bob."), "time trial mode: one at a time")
  w:waitFor(function() return w:sawMessage(A, "Alice: GO!") end, 10, "Alice's GO")
  w:chat(A, "/tg testevent stop")
  t.ok(w:chatHas(A, "Test event stopped - back to normal."))
  t.eq(w:state(A).phase, "idle")
  w:chat(A, "/tg testevent stop")
  t.ok(w:chatHas(A, "No test event is running."))
  -- not during a real challenge
  w:chat(A, "/tg start force")   -- (force: event 3 is unfinished on purpose)
  w:chat(A, "/tg testevent 1"); w:chat(A, "/tg quicktravel 1")
  t.ok(w:chatHas(A, "Test events only run when no challenge is going (/tg stop first)."))
  t.ok(w:chatHas(A, "Quick travel only works when no challenge is going."))
  w:assertClean()
end)

t.test("Quick travel: your car to the event's start, facing the first checkpoint", function()
  local w = World.new({ files = F.files(course()) })
  local A = w:join("Alice")
  w:buy(A, "covet", "base_M"); w:drive(A, p(3000, 200), 60); w:step(1.5)
  w:chat(A, "/tg quicktravel 2"); w:step(0.5)
  t.ok(w:chatHas(A, "Off to event 2's start."))
  t.eq(A.current.pos.x, 1500); t.eq(A.current.pos.y, 0)
  t.ok(math.abs(math.cos(A.current.yaw or 0) - 1) < 1e-6 or math.abs(math.sin(A.current.yaw or 0) - 1) < 1e-6,
    "facing along the course: " .. tostring(A.current.yaw))
  w:chat(A, "/tg quicktravel 3")
  t.ok(w:chatHas(A, "event 3 has no start yet."))
  w:assertClean()
end)
