-- Car classes (0.9.0): import every car's price + attributes, classes of rules + hand-picks, price adjustments,
-- and "needs N faults" in the dealership. Test cars (tests/lib/world.lua MODELS):
--   covet   Japan Hatchback 1988-1996  base_M $4,200 / sport_M $7,800 / gtz_M $14,000, all manual
--   pessima Japan Sedan     1988-1996  base_M $3,900 manual / gl_A $5,100 automatic
--   pickup  US Pickup (Truck) 1990-2010, miramar Japan Sedan 1970-1985, a trailer and cones
local t = require("t")
local World = require("world")
local F = require("fixtures")

local WIN = "Top Gear Challenge"
local function setup(w, A)
  w:chat(A, "/tg importprices")
  w:step(2)
end
local function jdm(w, A)   -- Japanese cars of the late 80s / 90s
  w:chat(A, "/tg class new jdm")
  w:chat(A, "/tg class rule jdm country Japan")
  w:chat(A, "/tg class rule jdm years 1986-1999")
  w:chat(A, "/tg class rule jdm type Car")
end

t.test("importprices reads every car in the game with its details, without flooding the dealer list", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A = w:join("Alice")
  setup(w, A)
  t.ok(w:chatHas(A, "Imported 10 trim prices from 6 models. Game prices are ON and saved to config.json."))
  local dealer = w:serverConfig().dealer
  local e = dealer.gamePrices.covet.gtz_M
  t.eq(e.price, 14000)
  t.eq(e.attrs.Country, "Japan"); t.eq(e.attrs.Transmission, "Manual"); t.eq(e.attrs.Years.min, 1988)
  t.eq(dealer.modelNames.covet, "Ibishu Covet")
  for _, c in ipairs(dealer.cars) do t.ok(c.model ~= "tsfb" and c.model ~= "cones", "props aren't added to the dealer list") end
  w:assertClean()
end)

t.test("a class of rules: only matching trims are sold, and the refusal says why", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A, B = w:join("Alice"), w:join("Bob")
  setup(w, A)
  jdm(w, A)
  t.ok(w:chatHas(A, "jdm: Country: Japan; Years 1986-1999; Type: Car - 5 trims, $3,900 to $14,000."))
  w:chat(A, "/tg class rule jdm transmission Manual")
  t.ok(w:chatHas(A, "- 4 trims, $3,900 to $14,000."), "the automatic Pessima drops out")
  w:chat(A, "/tg class use jdm")
  w:chat(A, "/tg start")
  t.ok(w:chatHas(B, "Today's cars: jdm - Country: Japan; Years 1986-1999; Type: Car; Transmission: Manual."))
  t.eq(w:buy(B, "pickup", "d15_M"), nil)
  t.ok(w:chatHas(B, "not in today's class (jdm): Country is United States"))
  t.eq(w:buy(B, "pessima", "gl_A"), nil)
  t.ok(w:chatHas(B, "not in today's class (jdm): Transmission is Automatic"))
  t.eq(w:buy(B, "miramar", "base_M"), nil)
  t.ok(w:chatHas(B, "not in today's class (jdm): Years 1970-1985 (needs 1986-1999)"))
  t.ok(w:buy(B, "pessima", "base_M"), "a matching trim sells")
  t.eq(w:state(B).cash, 10000 - 3900, "at its game price")
  w:step(2.5)
  local s = B.client.im.textOf(WIN)
  t.match(s, "TODAY'S CARS: jdm")
  t.ok(not s:find("D%-Series"), "the pickup isn't offered")
  w:chat(A, "/tg class use none")
  t.ok(w:chatHas(A, "Pick the class before /tg start - not during a challenge."))
  w:assertClean()
end)

t.test("over-budget trims show how many faults would buy them; faults then unlock them", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A = w:join("Alice")
  setup(w, A)
  jdm(w, A)
  w:chat(A, "/tg class price jdm covet/gtz_M 13000")    -- $3,000 over a $10,000 budget: 2 faults ($5,000)
  w:chat(A, "/tg class use jdm")
  w:chat(A, "/tg start")
  w:step(2.5)
  t.match(A.client.im.textOf(WIN), "%$13,000  Ibishu Covet gtz_M  %- needs 2 faults")
  t.ok(not A.client.im.hasButton("Buy##covet_gtz_M") and A.client.im.hasButton("Buy"), "no Buy button until it's affordable")
  t.eq(w:buy(A, "covet", "gtz_M"), nil)
  t.ok(w:chatHas(A, "over your $10,000 budget - 2 more faults would cover it (/tg fault take 2)"))
  w:chat(A, "/tg fault take 2")
  w:step(2.5)
  t.ok(A.client.im.hasButton("Buy"))
  A.client.im.click("Buy##covet_gtz_M")
  w:step(1)
  t.eq(A.current and A.current.configName, "gtz_M")
  t.eq(w:state(A).cash, 10000 + 5000 - 13000, "at the class price")
  w:assertClean()
end)

t.test("hand-picks and a price multiplier", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A = w:join("Alice")
  setup(w, A)
  jdm(w, A)
  w:chat(A, "/tg class exclude jdm covet/sport_M")
  w:chat(A, "/tg class include jdm pickup")
  w:chat(A, "/tg class multiplier jdm 0.5")
  w:chat(A, "/tg class show jdm")
  local s = table.concat(A.chat, "\n")
  t.ok(s:find("$1,950  Ibishu Pessima base_M  [pessima/base_M]", 1, true), "half price")
  t.ok(s:find("[pickup/d15_M]", 1, true), "the pickup is in by hand, though it breaks the rules")
  t.ok(not s:find("[covet/sport_M]", 1, true), "the excluded trim is out")
  w:chat(A, "/tg class clear jdm covet/sport_M")
  w:chat(A, "/tg class show jdm")
  t.ok(table.concat(A.chat, "\n"):find("[covet/sport_M]", 1, true), "clear puts it back")
  w:assertClean()
end)

t.test("no class: the normal dealer list, now with 'needs N faults' too", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A = w:join("Alice")
  w:chat(A, "/tg budget 5000")
  w:chat(A, "/tg start")
  w:step(2.5)
  local s = A.client.im.textOf(WIN)
  t.match(s, "%$7,500  Gavril D%-Series  %- needs 1 fault")
  t.match(s, "%$9,000  Bruckell Moonhawk  %- needs 2 faults")
  w:chat(A, "/tg dealer")
  t.ok(w:chatHas(A, "Gavril D-Series (pickup) - 1 trim, $7,500"))
  w:chat(A, "/tg dealer pickup")
  t.ok(w:chatHas(A, "$7,500  Gavril D-Series  (needs 1 fault)"))
  w:assertClean()
end)

t.test("a class with no cars won't start; the admin tab builds a class with buttons", function()
  local w = World.new({ files = F.files(F.twoRaces()) })
  local A = w:join("Alice")
  setup(w, A)
  w:chat(A, "/tg class new empty")
  w:chat(A, "/tg class use empty")
  w:chat(A, "/tg start")
  t.ok(w:chatHas(A, "Today's class (empty) has no cars"))
  t.eq(w:state(A) and w:state(A).phase or "idle", "idle")

  w:chat(A, "/tg menu"); w:step(2.5)
  local im = A.client.im
  t.ok(im.hasButton("> Edit"), "class list with Edit buttons (the one being edited is marked)")
  im.setText("##newclass", "trucks"); im.click("New class (one word)##clsnew"); w:step(2.5)
  t.ok(w:chatHas(A, "Made class trucks."))
  im.click("Edit##clsedit_trucks"); w:step(2.5)
  t.match(im.textOf(WIN), "CLASS trucks")
  -- the field list starts on Country; pick "Type" (4th) and add "Truck"
  im.click("Type##fld_type"); w:step(0.5)
  im.setText("##clsvalue", "Truck"); im.click("Add rule##clsaddrule"); w:step(2.5)
  t.ok(w:chatHas(A, "trucks: Type: Truck - 2 trims, $6,800 to $12,500."))
  t.ok(im.hasButton("Set price"), "the class's cars, each with a price box")
  im.click("Use##clsuse_trucks"); w:step(1)
  t.ok(w:chatHas(A, "Next challenge's cars: trucks"))
  w:assertClean()
end)
